TDEE/tdee_app/data/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from tdee_app.models import DailyStats, schema
from tdee_app import db
from tdee_app.data.forms import NewData, AddData
from flask_login import current_user, login_required
from flask_graphql import GraphQLView
from datetime import datetime
from collections import namedtuple

data = Blueprint('data', __name__)
cal_conver = 3500
Data =  namedtuple('Data', ['calories', 'weight'])

def list_past_week(day):
    ' takes in day and returns list of data for past 7 days if applicable'
    d = Data([],[])
   
    if day - 6 >= 0:
        for i in range(day - 6, day + 1):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    else:
        for i in range(day + 1):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    return d

def list_past_month(day):
    d = Data([],[])
    if day - 30 >= 0:
        for i in range(day - 30, day + 1):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    else:
        for i in range(day):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    return d
def get_average_weight_last_week(day):
    d = []
    for i in range(day):
        stats = DailyStats.query.filter_by(days=i-7, user_id=current_user.id).first()
        if stats:
            d.append(stats.weight)
    return sum(d)/len(d)

def tdee_week(d, day):
    ' returns weekly tdee given calories and weight throughout a week '
    if len(d.weight) > 1:
        delta =  get_average_weight_last_week(day) - (sum(d.weight)/len(d.weight))
    else:
        return 0
    tdee = (sum(d.calories)/len(d.calories)) - ((delta * 500 * (day % 7) / len(d.calories)))
    return round(tdee)

def tdee_month(d):
    if len(d.weight) > 1:
        delta = d.weight[-1] - d.weight[0]
    else:
        return 0
    tdee = (sum(d.calories)/len(d.calories)) - ((delta * cal_conver) / len(d.weight))
    return round(tdee)

def this_day_week_tdee(day):
    d = list_past_week(day)
    return str(tdee_week(d, day))

def this_day_month_tdee(day):
    d = list_past_month(day)
    return str(tdee_month(d))
##################################################################################################################
labels = [
    'JAN', 'FEB', 'MAR', 'APR',
    'MAY', 'JUN', 'JUL', 'AUG',
    'SEP', 'OCT', 'NOV', 'DEC'
]


values = []

colors = [
    "#F7464A", "#46BFBD", "#FDB45C", "#FEDCBA",
    "#ABCDEF", "#DDDDDD", "#ABCABC", "#4169E1",
    "#C71585", "#FF4500", "#FEDCBA", "#46BFBD"]

@data.route('/graphs', methods=["GET", "POST"])
@login_required
def graphs():
    data = DailyStats.query\
        .filter_by(user_id=current_user.id)\
        .order_by(DailyStats.date.desc()).all()
    for d in data:
        values.append(d.weight)
    line_labels=labels
    line_values=values
    return render_template('graphs.html', title='Graphs', max=17000, labels=line_labels, values=line_values)
##################################################################################################################
@data.route('/stats', methods=["GET", "POST"])
@login_required
def stats():
    data = DailyStats.query\
        .filter_by(user_id=current_user.id)\
        .order_by(DailyStats.date.desc()).all()
    if DailyStats.query.filter_by(date=datetime.today().date(), user_id=current_user.id).first():
        add_text = "Update Today's Data"
    else:
        add_text = 'Add Data'
    return render_template('stats.html', title='Stats', datas=data, text=add_text, calc_month=this_day_month_tdee, calc_week=this_day_week_tdee)


# add data to current date
@data.route('/new', methods=["GET", "POST"])
@login_required
def new():
    form = NewData()
    if form.validate_on_submit():
        stats = DailyStats(calories=form.calories.data, weight=form.weight.data, name=current_user, date=datetime.today().date(), days=(datetime.today().date()-current_user.start_date).days)
        # check if data already exists for current day
        if DailyStats.query.filter_by(date=datetime.today().date(), user_id=current_user.id).first():
            remove_stats = DailyStats.query.filter_by(date=datetime.today().date(), user_id=current_user.id).first()
            db.session.delete(remove_stats)
            flash('Data Updated', 'success')
        else:
            flash('Data Added', 'success')
        db.session.add(stats)
        db.session.commit()
        return redirect(url_for('main.home'))
    elif request.method == 'GET':
        if DailyStats.query.filter_by(date=datetime.today().date(), user_id=current_user.id).first():
            form.calories.data = DailyStats.query\
                .filter_by(date=datetime.today().date(), user_id=current_user.id)\
                .first().calories
            form.weight.data = DailyStats.query\
                .filter_by(date=datetime.today().date(), user_id=current_user.id)\
                .first().weight
            return render_template('new.html', title='New', form=form, text='Update')
    return render_template('new.html', title='New', form=form, text='Add')

# add data to past days
@data.route('/add', methods=["GET", "POST"])
@login_required
def add_data():
    form = AddData()
    if form.validate_on_submit():
        # date_conver = datetime.strptime(form.date.data, '%Y-%m-%d')
        stats = DailyStats(calories=form.calories.data, weight=form.weight.data, name=current_user, date=form.date.data, days=(form.date.data-current_user.start_date).days)
        # removes the previous stats for day if data for day already exists
        # patched out
        if DailyStats.query.filter_by(date=form.date.data, user_id=current_user.id).first():
            remove_stats = DailyStats.query.filter_by(date = form.date.data, user_id=current_user.id).first()
            db.session.delete(remove_stats)
            flash('Data Updated', 'success')
        else:
            flash(f'Data Added for day {stats.days}, ', 'success')
        db.session.add(stats)
        db.session.commit()
        return redirect(url_for('data.add_data'))
  
    return render_template('add.html', title='Add Data', form=form, text='Add')

@data.route('/<int:data_id>/delete', methods=['POST'])
@login_required
def delete_data(data_id):
    data = DailyStats.query.get_or_404(data_id)
    if data.name != current_user:
        abort(403)
    db.session.delete(data)
    db.session.commit()
    flash(f'Data for date {data.date} deleted.', 'danger')
    return redirect(url_for('data.stats'))

    
    
# graphql
data.add_url_rule(
    '/graphql',
    view_func=GraphQLView.as_view(
        'graphql',
        schema=schema,
        graphiql=True # for having the GraphiQL interface
    )
)

TDEE/tdee_app/main/routes.py
from flask import render_template, Blueprint
from tdee_app.models import DailyStats
from flask_login import login_required, current_user
from datetime import datetime
# from tdee_app.calc import calc_tdee
from collections import namedtuple


main = Blueprint('main', __name__)
##########################################################################################################################
cal_conver = 3500
Data =  namedtuple('Data', ['calories', 'weight'])

def list_past_month(day):
    d = Data([],[])
    if day - 30 >= 0:
        for i in range(day - 30, day + 1):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    else:
        for i in range(day):
            stats = DailyStats.query.filter_by(days=i, user_id=current_user.id).first()
            if stats:
                d.calories.append(stats.calories)
                d.weight.append(stats.weight)
    return d

def tdee_month(d):
    if len(d.weight) > 1:
        delta = d.weight[-1] - d.weight[0]
    else:
        return 0
    tdee = (sum(d.calories)/len(d.calories)) - ((delta * cal_conver) / len(d.weight))
    return round(tdee)

def this_day_month_tdee(day):
    d = list_past_month(day)
    return str(tdee_month(d))

#################################################################################################

@main.route('/')
@main.route('/home')
@login_required
def home():
    data = DailyStats.query\
        .filter_by(user_id=current_user.id)\
        .order_by(DailyStats.date.desc()).all()
    if DailyStats.query.filter_by(date=datetime.today().date(), user_id=current_user.id).first():
        add_text = "Update Today's Data"
    else:
        add_text = 'Add Data'
    # gets most recent date
    d = data[0].date
    tdee = this_day_month_tdee((d-current_user.start_date).days)
    days = len(DailyStats.query.filter_by(user_id=current_user.id).all())
    return render_template('home.html', datas=data, text=add_text, tdee=tdee, days=days)

@main.route('/about')
def about():
    return render_template('about.html', title='About')

TDEE/tdee_app/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from tdee_app.models import User
from tdee_app import db, bcrypt
from tdee_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=hashed_password, start_weight=form.start_weight.data)
        db.session.add(user)
        db.session.commit()
        flash(f'Account Created For {form.username.data}.', category='success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Incorrect credentials', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout', methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/profile', methods=["GET", "POST"])
@login_required
def profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.start_date = form.start_date.data
        current_user.start_weight = form.start_weight.data
        db.session.commit()
        flash('Account Updated.', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.start_date.data = current_user.start_date
        form.start_weight.data = current_user.start_weight
        
    return render_template('profile.html', title='Profile', form=form)

TDEE/tdee_app/templates/about.html
{% extends "layout.html" %}
{% block content %}
<h5>TDEE tracker is a web app that calculates your TDEE.</h5>
<b>For best results, enter data everyday.</b>
<b>If you do not know your calories for a day, estimate the number of calories.</b>
<b>If you do not know your weight for a day, use the weight from the previous day.</b>
{% endblock content %}

TDEE/tdee_app/templates/add.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section col-md-8 align-self-center">
    
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom text-center">Add Data</legend>
            <div class="form-group">
                    {{ form.date.label(class="form-control-label") }}
    
                    {% if form.date.errors %}
                    {{ form.date(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.date.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.date(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            <div class="form-group">
                {{ form.calories.label(class="form-control-label") }}

                {% if form.calories.errors %}
                {{ form.calories(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.calories.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.calories(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.weight.label(class="form-control-label") }}
                {% if form.weight.errors %}
                {{ form.weight(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.weight.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.weight(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info col-md-12 mr-auto") }}
        </div>
    </form>
</div>
{% endblock content %}

TDEE/tdee_app/templates/graphs.html
{% extends "layout.html" %}
{% block content %}

<meta charset="utf-8">
<title>Chart.js </title>

<!-- import plugin script -->
<script src="static/Chart.min.js"></script>
<h1>Flask Chart.js</h1>
<!-- bar chart canvas element -->
<canvas id="chart" width="600" height="400"></canvas>

<script></p>
<p>   // bar chart data<br />
   var barData = {<br />
   labels : [],<br />
   datasets : [<br />
      {<br />
            fillColor: "rgba(151,187,205,0.2)",<br />
            strokeColor: "rgba(151,187,205,1)",<br />
            pointColor: "rgba(151,187,205,1)",<br />
            pointStrokeColor: "#fff",<br />
            pointHighlightFill: "#fff",<br />
            pointHighlightStroke: "rgba(151,187,205,1)",<br />
            bezierCurve : false,<br />
            data : []<br />
      }]<br />
   }</p>
<p>    Chart.defaults.global.animationSteps = 50;<br />
    Chart.defaults.global.tooltipYPadding = 16;<br />
    Chart.defaults.global.tooltipCornerRadius = 0;<br />
    Chart.defaults.global.tooltipTitleFontStyle = "normal";<br />
    Chart.defaults.global.tooltipFillColor = "rgba(0,0,0,0.8)";<br />
    Chart.defaults.global.animationEasing = "easeOutBounce";<br />
    Chart.defaults.global.responsive = false;<br />
    Chart.defaults.global.scaleLineColor = "black";<br />
    Chart.defaults.global.scaleFontSize = 16;</p>
<p>   // get bar chart canvas<br />
   var mychart = document.getElementById("chart").getContext("2d");</p>
<p>   steps = 10<br />
   max = 10<br />
   // draw bar chart<br />
   var LineChartDemo = new Chart(mychart).Line(barData, {<br />
        scaleOverride: true,<br />
        scaleSteps: steps,<br />
        scaleStepWidth: Math.ceil(max / steps),<br />
        scaleStartValue: 0,<br />
        scaleShowVerticalLines: true,<br />
        scaleShowGridLines : true,<br />
        barShowStroke : true,<br />
        scaleShowLabels: true,<br />
        bezierCurve: false,</p>
<p>   });</p>
<p></script>
{% endblock content %}

TDEE/tdee_app/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <a href="{{ url_for('data.new') }}" class="btn btn-outline-info col-md-12 mr-auto">{{ text }}</a>

</div>
<div class="row">
  <article class="media content-section col-md-12 mr-auto">
    <div class="media-body col">
      <h5 class="cr-2">You have been tracking for {{ days }} days</h5>
      <h3 class="cr-2">Monthly TDEE: {{ tdee }}</h3>

    </div>
  </article>
</div>
{% endblock content %}

TDEE/tdee_app/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>TDEE Tracker</title>
  {% endif %}
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-color fixed-top">
      <div class="container">
        <a class="navbar-brand mr-3" href="/">TDEE Tracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
          aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('data.graphs') }}">Graphs</a>
            <a class="nav-item nav-link" href="{{ url_for('data.stats') }}">Stats</a>
            {% else %}
            {% endif %}
          </div>
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('users.profile') }}"> {{ current_user.username }}'s Profile</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container ">
    <div class="row align-self-center">
      <div class="center container-fluid col-lg-8 ">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}

      </div>
  </main>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

TDEE/tdee_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="col"></div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom text-center">Log In</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}

            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info col-md-12 mr-auto") }}
            <a class="btn btn-outline-info col-md-12 mr-auto" href="{{ url_for('users.register') }}">Need An Account?</a>
        </div>
    </form>
</div>
{% endblock content %}

TDEE/tdee_app/templates/new.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section col-md-8 align-self-center">
    <div class="col"></div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom text-center">Daily Data</legend>
            <div class="form-group">
                {{ form.calories.label(class="form-control-label") }}

                {% if form.calories.errors %}
                {{ form.calories(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.calories.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.calories(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.weight.label(class="form-control-label") }}
                {% if form.weight.errors %}
                {{ form.weight(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.weight.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.weight(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info col-md-12 mr-auto") }}
        </div>
    </form>
</div>
{% endblock content %}

TDEE/tdee_app/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="col"></div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom text-center">{{ current_user.username}}'s Starting Stats</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.start_date.label(class='form-control-label') }}
                {% if form.start_date.errors %}
                {{ form.start_date(class='form-control form-control-lg is-invalid') }}
                <div class="invalid-feedback">
                    {% for error in form.start_date.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.start_date(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.start_weight.label(class="form-control-label") }}
                {% if form.start_weight.errors %}
                {{ form.start_weight(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.start_weight.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.start_weight(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info col-md-12 mr-auto") }}
        </div>
    </form>
    <div class="col"></div>
</div>
{% endblock content %}

TDEE/tdee_app/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="col"></div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom text-center">Create An Account</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                    {{ form.start_weight.label(class="form-control-label") }}
    
                    {% if form.start_weight.errors %}
                    {{ form.start_weight(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.start_weight.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.start_weight(class="form-control form-control-lg") }}
                    {% endif %}
    
                </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info col-md-12 mr-auto") }}
            <a class="btn btn-outline-info col-md-12 mr-auto" href="{{ url_for('users.login') }}">Already Have An Account?</a>
        </div>
    </form>
    <div class="col"></div>
</div>
{% endblock content %}

TDEE/tdee_app/templates/stats.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
    <a href="{{ url_for('data.add_data') }}" class="btn btn-outline-info col-md-8 mr-auto">Add Data for Date</a>
    <a href="{{ url_for('data.new') }}" class="btn btn-outline-info col-md-4 mr-auto">{{ text }}</a>


</div>
<div class="row">
    {% for data in datas %}
    <article class="media content-section col-md-6 mr-auto">
        <div class="media-body col">
            <h5 class="cr-2">{{ data.date }}</h5>
            <h6 class="cr-2">{{ data.days }} days since start</h6>
            <h5 class="cr-2">{{ data.user_id.username }}</h5>
            <h5 class="cr-2">{{ data.calories }} Calories</h5>
            <h5 class="cr-2">{{ data.weight }} LB</h5>
            <div class=row>
                <form action="{{ url_for('data.delete_data', data_id=data.id)}}" method="POST">
                    <input type="submit" class="btn btn-info btn-sm m-1" value="Update"></input>
                </form>
                <form action="{{ url_for('data.delete_data', data_id=data.id)}}" method="POST">
                    <input type="submit" class="btn btn-danger btn-sm m-1" value="Delete"></input>
                </form>
            </div>
        </div>
        <div class="media-body">
            <h6 class="mr-2 cr-2">Weekly TDEE: </h6>
            {% if data.days > 7 %}
            <h3 class="cr-2 mr-2 border border-warning">{{ calc_week(data.days) }}</h3>
            {% else %}
            <h6 class="cr-2 mr-2 border border-warning">Data Pending</h6>
            {% endif %}
            <h6 class="mr-2 cr-2">Monthly TDEE: </h6>
            <h3 class="cr-2 mr-2  border border-info">{{ calc_month(data.days) }}</h3>

        </div>
    </article>
    {% endfor %}
</div>
{% endblock content %}